#!/usr/bin/env bash
set -e

# don't loop if files don't exist
shopt -s nullglob

if [[ ! -d dist ]] ; then
    printf "This needs to be run from the root of the repo\n"
    exit 1
fi

# exit if TRAVIS_TAG is empty, no need to release anything
if [ -z "${TRAVIS_TAG}" ]; then
  exit 0
fi

export "PATH=$(pwd)/tools/cross/bin:$PATH"

# get user and repo names
USERNAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f1)
REPONAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f2)

# release
github-release release \
  --user "${USERNAME}" \
  --repo "${REPONAME}" \
  --tag "${TRAVIS_TAG}" \
  --name "${TRAVIS_TAG}" \
  --description "$(cat $(pwd)/dist/release.md)" || true

# binaries
for i in "$(pwd)/dist/"*.tar.gz; do
  name=$(basename ${i})
  gpg -u 0x3B2FD161 --output "${i}.sig" --detach-sig "${i}"
  github-release upload \
    --user "${USERNAME}" \
    --repo "${REPONAME}" \
    --tag "${TRAVIS_TAG}" \
    --name "${name}" \
    --file "${i}"
  github-release upload \
    --user "${USERNAME}" \
    --repo "${REPONAME}" \
    --tag "${TRAVIS_TAG}" \
    --name "${name}.sig" \
    --file "${i}.sig"
done
