#
# This file has been generated by tools/gen-deps.sh
#

src/justc-envdir/justc-envdir.o src/justc-envdir/justc-envdir.lo: src/justc-envdir/justc-envdir.c

justc-envdir: EXTRA_LIBS :=
justc-envdir: src/justc-envdir/justc-envdir.o -lskarnet
